"""
Gaussian observation noise wrapper (sensor shift).

Phase 5 — evaluation-time perturbation only.
Training code is never modified; this wrapper is applied post-hoc.

Threat model (from docs/threat_model.md):
  Injection point: obs_env → perturbation → policy
  Additive Gaussian noise in normalised observation space.
  Severity parameter: σ (sigma).
"""

from __future__ import annotations

import numpy as np
import gymnasium


class GaussianObsNoiseWrapper(gymnasium.ObservationWrapper):
    """Add i.i.d. Gaussian noise to every observation returned by the env.

    Noise is generated by a private, local NumPy RandomState so that:
      - It does NOT share state with global NumPy or Torch RNGs.
      - Given the same `seed`, the noise sequence is fully deterministic
        regardless of external RNG usage.

    When ``sigma == 0.0`` the wrapper is a no-op (exact pass-through),
    which allows uniform treatment across the σ severity grid.

    Observations are NOT clipped after noise injection; the wrapper is
    purely additive as specified in the threat model.

    Args:
        env:   Wrapped Gymnasium environment.
        sigma: Standard deviation of the Gaussian noise (in observation
               space units). 0.0 disables noise entirely.
        seed:  Integer seed for the private noise RNG.
    """

    def __init__(self, env: gymnasium.Env, sigma: float, seed: int) -> None:
        super().__init__(env)
        self.sigma = float(sigma)
        self.rng   = np.random.RandomState(seed)

    def observation(self, obs: np.ndarray) -> np.ndarray:
        """Apply (or skip) additive Gaussian noise and return float32 obs."""
        obs = np.asarray(obs, dtype=np.float32)
        if self.sigma == 0.0:
            return obs
        noise = self.rng.randn(*obs.shape).astype(np.float32)
        return obs + self.sigma * noise
